### ISSUE TITLE
Sprint review 01

### ISSUE THREAD

**Issue by anabollain** [Adalab/project-promo-r-module-2-team-7#10]
- Introducción: trabajo individual/pair @martcastrillo 
- Zeplin/diseño (HTML/CSS): fantasía 
- Estructura proyecto: variables/mixins/partials/sass 
- Interacciones: colapsable (objetivo sprint 1 ok, funcionalidad pendiente) / reset / preview fill (añadir imagen próximo sprint) / paleta colores design / share card
- Revisión del sprint pasado y planteamiento del siguiente

**Comment by martcastrillo** [comment]
### **ITRO**

> Hola, somos un equipo de trabajo formado por Laura, Ana, Celia y yo, Marta. El proyecto que hemos preparado es una web que permite crear tarjetas de contacto. Esta web se compone de una landing page y la página de creación de tarjetas propiamente dicha. Nuestra metodología de trabajo al inicio, después de establecer las que iban a ser nuestras dinámicas, fue trabajar en la estructura de manera conjunta, en los estilos de CSS de manera individual y en cuanto a las interacciones trabajamos en pair para ser más eficientes. 

### **DISEÑO**

> Hemos podido observar ciertos tipos de desajustes en el proyecto de zepplin que no nos han encajado, como son los márgenes superiores en el caso de la landing page, el del botón o los márgenes del logo en la página de creación de tarjetas hacía que quedase un poco raro en nuestra opinión, en estos casos nos hemos tomado ciertas libertades, como libertades hemos tomado a la hora de crear detalles añadidos como transiciones en los _hover_ que hemos incluido en prácticamente toda la botonería o elemento clicable. En cuanto al diseño hemos tomado la landing page como que tiene una altura del total de la pantalla tanto en movil como en tablet, asi como en la versión de tablet y desktop de la pagina de diseño de las tarjetas

**Comment by anabollain** [comment]
Estructura

Os voy a hablar un poco de cómo hemos estructurado el proyecto. Está organizado en partials para poder trabajar de forma independiente, tanto en html como en Sass. También hemos utilizado mixins para optimizar codigo y variables, así como una función para traducir píxeles a rems y asegurar que tanto el diseño como el texto sean responsive. 

Interacciones 

Las interacciones de JavaScript también están divididas por tareas. La primera consiste en elegir la paleta de colores que te interese como usuario y que puedas ver los cambios reflejados en la tarjeta (con un event listener en cada input que aplica o elimina clases de Css). Una segunda interaccion para el apartado fill, de forma que la información que se va rellenando también se va trasladando a la tarjeta (tanto texto como los enlaces a páginas, contacto y movil). Y, por último, un boton reset que al pulsar sobre él elimina toda la información de los inputs y la tarjeta,  reseteando también la paleta de colores a su estado inicial.

**Comment by lvaldenebro** [comment]
interacciones: 

1. comentar dos interacciones con un funcionamiento similar, se les agrega o elimina la clase:
- formulario que pliega:  (5_create-card.js --> enseñar) --> a mejorar, ahora mismo actúan por separado
- transición para crear el enlace (05_create-card.js -> enseñar)

2. formulario: 
- todo creado excepto el añadir imagen, que está preparado para recibir la librería
- no tenemos marcados cuáles son los campos obligatorios en la ficha de proyecto, ¿cuáles queremos que sean? -> esperar respuesta de PO
- al no tener un botón de submit, se nos eliminan las condiciones de campos de tipo específicos como email y telf, ¿alguna recomendación?

**Comment by celiamartin11** [comment]
vengo hablar de lo que tenemos pensado hacer y entregar en el próximo
sprint.
Para empezar, en la página para crear la carta personalizada tenemos
pensado que a la hora de abrir los 3 pasos que hay que hacer para poder
crearla, solo se pueda abrir uno. Es decir, que al abrir uno, los otros dos
esten cerrados y así sucesivamente.
También tenemos pendiente que el usuario pueda  añadir su imagen, y que
esta se vea reflejada en la carta, y finalmente poner el enlace de  twitter
para poder compartirla a través de esta aplicación.
Esperamos que os haya gustado, y muchas gracias por vuestra atención.
